### ISSUE TITLE
Getting Hot Module Replacement [HMR] to work

### ISSUE THREAD

**Issue by laggingreflex** [start-runner/webpack-dev-server#1]
I had to spend some time to figure out how to get HMR to work with this because I was mainly used to the CLI which makes it pretty easy with the `--hot --inline`  switches. 

With this you have to do 

1. Insert HMR plugin in your `webpack.config.js`: `new webpack.HotModuleReplacementPlugin()`
2. Insert these 2 files in your entry point(s):

       'webpack/hot/dev-server',
       'webpack-dev-server/client?',

3. Pass `{hot: true}` in `devServerOptions`

What if `start-webpack-dev-server` could do all this for the user automatically? The `{hot: true}` option could do #<n>1</n>, and it could accept an additional `{inline: true}` option that does #<n>2</n>?

**Comment by deepsweet** [comment]
sounds reasonable from some point of view, but at the same time I want to keep tasks as clean and simple as possible. so here is 2 possible solutions:

1. create a separate task like `start-webpack-dev-server-hot`, a simple wrapper like this:

```js
import Start from 'start';
import webpackDevServer from 'start-webpack-dev-server';

export default (config, userDevServerOptions, userServerOptions) => () => {
  return function webpackDevServerHot(log, reporter) {
    const start = Start(reporter);
    const hotConfig = {
      ...config,
      entry: [
        ...config.entry,
        // hot entries
      ],
      plugins: [
        ...config.plugins,
        // hot plugin
      ]
    };
    const hotDevServerOptions = {
      ...userDevServerOptions,
      hot: true
    };

    return start(
      webpackDevServer(hotConfig, hotDevServerOptions, userServerOptions)
    );
  };
};
```

and I really like it 😼  imo composition is much better than trying to make one tool that can handle many options and scenarios. you have already done good work in your PR, just try to add some of those changes to the stub above.

2. [webpack-blocks](https://github.com/andywer/webpack-blocks). from another point of view it's a problem of webpack's complex solution(s) just to make HMR work. so maybe it's a good idea to use something like webpack-blocks (see their [dev-server-2](https://github.com/andywer/webpack-blocks/tree/master/packages/dev-server2) block) as some kind of config presets.

**Comment by laggingreflex** [comment]
Sounds good. I've created [`start-webpack-dev-server-hot`](https://github.com/laggingreflex/start-webpack-dev-server-hot).
